/**
 * This file is generated by sveltekit-api-fetch.
 * Do not edit it, as it will be overwritten.
 * Learn more here: https://github.com/Guibi1/sveltekit-api-fetch
 */

type AllowedUrls = {
    "/api/user": {
        GET: null;
    };
    "/api/user/avatar": {
        POST: { avatar: string };
    };
    "/api/settings/firstDayOfTheWeek": {
        PUT: { firstDayOfTheWeek: string };
    };
    "/api/settings/colorScheme": {
        PUT: { colorScheme: string };
    };
    "/api/schedule": {
        POST: { periods: { name: string; _id: string; timeStart: string; timeEnd: string }[] };
        DELETE: { period: { name: string; _id: string; timeStart: string; timeEnd: string } };
        GET: null;
    };
    "/api/notifications": {
        POST: { kind: string; receiverId: string };
        DELETE: { notificationId: string };
        GET: null;
    };
    "/api/images/book/[filename]": {
        GET: null;
    };
    "/api/groups": {
        POST: { usersId: string[] };
        DELETE: { groupId: string };
        GET: null;
    };
    "/api/groups/name": {
        POST: { groupId: string; name: string };
    };
    "/api/groups/members": {
        POST: { groupId: string };
    };
    "/api/groups/invite": {
        POST: { groupId: string; usersId: string[] };
    };
    "/api/friends": {
        POST: { friendId: string };
        DELETE: { friendId: string };
        GET: null;
    };
    "/api/book": {
        DELETE: { bookId: string };
    };
};
