/**
 * This file is generated by sveltekit-api-fetch.
 * Do not edit it, as it will be overwritten.
 * Learn more here: https://github.com/Guibi1/sveltekit-api-fetch
 */

type ProjectAPI = {
    GET: {
        "/api/user": never;
        "/api/schedule": never;
        "/api/notifications": never;
        "/api/images/book/[filename]": never;
        "/api/groups": never;
        "/api/friends": never;
    };
    POST: {
        "/api/user/avatar": { avatar: string };
        "/api/schedule": { periods: { name: string; id: number; timeStart: string; timeEnd: string }[] };
        "/api/notifications": { kind: string; receiverId: string };
        "/api/groups": { usersId: string[] };
        "/api/groups/name": { groupId: number; name: string };
        "/api/groups/members": { groupId: number };
        "/api/groups/invite": { groupId: number; usersId: string[] };
        "/api/friends": { friendId: string };
    };
    PUT: {
        "/api/settings/colorScheme": { colorScheme: string };
    };
    DELETE: {
        "/api/schedule": { period: { name: string; id: number; timeStart: string; timeEnd: string } };
        "/api/notifications": { notificationId: number };
        "/api/groups": { groupId: number };
        "/api/friends": { friendId: string };
        "/api/book": { bookId: number };
    };
};
