#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

command_exists () {
    command -v "$1" >/dev/null 2>&1
}

# Workaround for pnpm
if command_exists pnpm; then
    pnpm dlx pretty-quick --staged
else
    npx pretty-quick --staged
fi
